import img1 from "../img/test-quiz-svgrepo-com.png";
import img2 from "../img/task-assignment-task-homework-assignment-svgrepo-com.png";
import img3 from "../img/Path 519.png";
export const CourseworkList = [
  {
    img: img2,
    name: "Week 1: Assignment #1",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Submitted",
    grade: "8",
    cName: "green",
  },
  {
    img: img2,
    name: "Week 1: Assignment #2",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Not Submitted",
    grade: "",
    cName: "gray",
  },
  {
    img: img2,
    name: "Week 2: Assignment #1",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Overdue",
    grade: "",
    cName: "red",
  },
  {
    img: img2,
    name: "Week 2: Assignment #2",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Overdue",
    grade: "",
    cName: "red",
  },
  {
    img: img1,
    name: "Quiz 1",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Finished",
    grade: "8",
    cName: "green",
  },
  {
    img: img1,
    name: "Quiz 2",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Not Submitted",
    grade: "",
    cName: "gray",
  },

  {
    img: img3,
    name: "Exam: Final",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Not Submitted",
    grade: "",
    cName: "gray",
  },
  {
    img: img3,
    name: "Exam: Final",
    date: "may 26",
    points: "10 points",
    submit: "submit",
    status: "Not Submitted",
    grade: "",
    cName: "gray",
  },
];
